<?php

function agileissues_public_landing_page() {
  return __FUNCTION__;
}

function agileissues_project_landing_page($project) {
return __FUNCTION__;
}

function agileissues_backlog_landing_page($project, $backlog = NULL) {
return __FUNCTION__;
}

function agileissues_sprint_landing_page($project, $sprint = NULL) {
return __FUNCTION__;
}

function agileissues_story_landing_page($story) {
return __FUNCTION__;
}

function agileissues_task_landing_page($task) {
return __FUNCTION__;
}
